[package]
name = "polygon_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.5"
serde_json = "1.0.120"
serde = { version = "1.0.204", features = ["derive"] }
log = "0.4.22"
